import { ArrowLeft, Check, ChevronLeft, ChevronRight, Plus, Search, UserPlus } from 'lucide-react'
import { useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { toast } from 'sonner'
import { PageHeader } from '../../components/admin/PageHeader'
import { EmptyState, ErrorState, LoadingState, Modal } from '../../components/ui'
import { useSupabaseList } from '../../hooks/useSupabaseList'
import { supabase } from '../../lib/supabase'
import { rupiah } from '../../lib/utils'
import { statusLabels, type Customer, type OrderItem, type OrderStatus, type Reward } from '../../types'

type DraftItem = OrderItem & { measurements: Record<string, string> }
const blankItem = (): DraftItem => ({ clothing_type: '', model: '', quantity: 1, unit_price: 0, measurements: { chest: '', waist: '', length: '', shoulder: '', sleeve: '' } })

export function AddOrderPage() {
  const navigate = useNavigate(); const customers = useSupabaseList<Customer>('customers', '*', 'name'); const rewardSource = useSupabaseList<Reward>('rewards', '*', 'created_at'); const rewards = { ...rewardSource, data: rewardSource.data.filter(x => x.reward_type !== 'item') };
  const [customer, setCustomer] = useState<Customer | null>(null); const [customerOpen, setCustomerOpen] = useState(false); const [newCustomerOpen, setNewCustomerOpen] = useState(false); const [query, setQuery] = useState(''); const [page, setPage] = useState(1)
  const [items, setItems] = useState<DraftItem[]>([blankItem()]); const [rewardId, setRewardId] = useState(''); const [date, setDate] = useState(''); const [status, setStatus] = useState<OrderStatus>('received'); const [notes, setNotes] = useState(''); const [busy, setBusy] = useState(false)
  const filtered = useMemo(() => customers.data.filter(x => `${x.name} ${x.whatsapp}`.toLowerCase().includes(query.toLowerCase())), [customers.data, query]); const pageSize = 6; const visible = filtered.slice((page - 1) * pageSize, page * pageSize); const pages = Math.max(1, Math.ceil(filtered.length / pageSize))
  const subtotal = items.reduce((sum, item) => sum + item.quantity * item.unit_price, 0); const reward = rewards.data.find(x => x.id === rewardId); const discount = reward?.reward_type === 'discount_percent' ? Math.min(subtotal, subtotal * (reward.discount_value ?? 0) / 100) : reward?.reward_type === 'discount_amount' ? Math.min(subtotal, reward.discount_value ?? 0) : 0; const total = Math.max(0, subtotal - discount)
  const updateItem = (index: number, patch: Partial<DraftItem>) => setItems(items.map((item, i) => i === index ? { ...item, ...patch } : item))
  const save = async () => { if (!customer || items.some(x => !x.clothing_type || !x.model || x.unit_price < 0)) { toast.error('Pilih pelanggan dan lengkapi semua item.'); return } setBusy(true); const result = await supabase.rpc('create_admin_order', { p_name: customer.name, p_whatsapp: customer.whatsapp, p_address: customer.address, p_notes: notes || null, p_items: items.map(x => ({ clothing_type: x.clothing_type, model: x.model, quantity: x.quantity, unit_price: x.unit_price, measurements: x.measurements })), p_estimated_completion: date || null, p_status: status, p_reward_id: rewardId || null }); setBusy(false); if (result.error) toast.error(result.error.message); else { toast.success(`Pesanan ${result.data} berhasil dibuat`); navigate('/mz-admin/pesanan') } }
  return <><button className="mb-5 inline-flex items-center gap-2 text-sm font-bold text-sage-700" onClick={() => navigate('/mz-admin/pesanan')}><ArrowLeft size={16} /> Kembali ke pesanan</button><PageHeader title="Tambah pesanan" description="Buat pesanan dengan item, ukuran, harga, dan reward pelanggan." />
    <div className="grid gap-6 xl:grid-cols-[1fr_22rem]">
      <div className="space-y-6">
        <section className="card p-5"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-bold">Pelanggan</h2><p className="mt-1 text-xs text-slate-500">Pilih pelanggan yang sudah tersimpan.</p></div><button className="btn-secondary" onClick={() => setNewCustomerOpen(true)}><UserPlus size={16} /> Pelanggan baru</button></div>{customer ? <div className="flex items-center justify-between rounded-2xl bg-sage-50 p-4"><div><b>{customer.name}</b><p className="mt-1 text-sm text-slate-500">{customer.whatsapp}</p><p className="mt-1 text-xs text-slate-400">{customer.address || 'Alamat belum diisi'}</p></div><button className="btn-secondary" onClick={() => setCustomerOpen(true)}>Ganti</button></div> : <button className="flex w-full items-center justify-between rounded-2xl border border-dashed border-sage-300 p-4 text-left hover:bg-sage-50" onClick={() => setCustomerOpen(true)}><span><b>Pilih pelanggan</b><small className="mt-1 block text-xs text-slate-500">Search dan pilih dari daftar</small></span><Search size={18} className="text-sage-600" /></button>}</section>
        <section className="card p-5"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-bold">Item pesanan</h2><p className="mt-1 text-xs text-slate-500">Setiap item dapat memiliki ukuran berbeda.</p></div><button className="btn-secondary" onClick={() => setItems([...items, blankItem()])}><Plus size={16} /> Tambah item</button></div><div className="space-y-4">{items.map((item, index) => <div key={index} className="rounded-2xl border border-sage-100 bg-sage-50/30 p-4"><div className="mb-3 flex justify-between"><b className="text-sm">Item {index + 1}</b>{items.length > 1 && <button className="text-xs font-bold text-red-500" onClick={() => setItems(items.filter((_, i) => i !== index))}>Hapus</button>}</div><div className="grid gap-3 sm:grid-cols-2"><label><span className="label">Jenis pakaian</span><input className="input" placeholder="Contoh: Seragam" value={item.clothing_type} onChange={e => updateItem(index, { clothing_type: e.target.value })} /></label><label><span className="label">Model pakaian</span><input className="input" placeholder="Contoh: Kemeja lengan panjang" value={item.model} onChange={e => updateItem(index, { model: e.target.value })} /></label><label><span className="label">Jumlah</span><input className="input" type="number" min="1" value={item.quantity} onChange={e => updateItem(index, { quantity: Math.max(1, Number(e.target.value) || 1) })} /></label><label><span className="label">Harga satuan (Rp)</span><input className="input" type="number" min="0" placeholder="0" value={item.unit_price || ''} onChange={e => updateItem(index, { unit_price: Math.max(0, Number(e.target.value) || 0) })} /></label></div><div className="mt-4 rounded-xl border border-sage-100 bg-white p-3"><b className="text-xs text-sage-800">Ukuran item ini</b><div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-5">{[['chest','Dada'],['waist','Pinggang'],['length','Panjang'],['shoulder','Bahu'],['sleeve','Lengan']].map(([key, label]) => <label key={key}><span className="mb-1 block text-[10px] font-bold text-slate-500">{label} (cm)</span><input className="input h-10 text-sm" placeholder="-" value={item.measurements[key] ?? ''} onChange={e => updateItem(index, { measurements: { ...item.measurements, [key]: e.target.value } })} /></label>)}</div></div><div className="mt-3 text-right text-sm font-bold text-sage-700">Total item: {rupiah(item.quantity * item.unit_price)}</div></div>)}</div></section>
        <section className="card p-5"><h2 className="font-bold">Penyelesaian</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><label><span className="label">Estimasi selesai</span><input className="input" type="date" value={date} onChange={e => setDate(e.target.value)} /></label><label><span className="label">Status awal</span><select className="input" value={status} onChange={e => setStatus(e.target.value as OrderStatus)}>{Object.entries(statusLabels).map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select></label></div><label className="mt-4 block"><span className="label">Catatan</span><textarea className="input min-h-24" value={notes} onChange={e => setNotes(e.target.value)} placeholder="Catatan pengerjaan" /></label></section>
      </div>
      <aside className="h-fit space-y-4 xl:sticky xl:top-24"><section className="card p-5"><h2 className="font-bold">Ringkasan harga</h2><div className="mt-5 space-y-3 text-sm"><div className="flex justify-between"><span className="text-slate-500">Subtotal item</span><b>{rupiah(subtotal)}</b></div><div className="flex justify-between text-emerald-700"><span>Diskon reward</span><b>- {rupiah(discount)}</b></div><div className="flex justify-between border-t border-sage-100 pt-3 text-base"><b>Total pesanan</b><b className="text-sage-700">{rupiah(total)}</b></div></div></section><section className="card p-5"><h2 className="font-bold">Reward pelanggan</h2>{customer?.available_rewards ? <><p className="mt-1 text-xs text-slate-500">Pelanggan memiliki {customer.available_rewards} reward aktif.</p><select className="input mt-4" value={rewardId} onChange={e => setRewardId(e.target.value)}><option value="">Tidak menggunakan reward</option>{rewards.data.filter(x => x.is_active && (x.stock === null || (x.stock ?? 0) > 0)).map(x => <option key={x.id} value={x.id}>{x.name}{x.reward_type === 'discount_percent' ? ` · ${x.discount_value}%` : x.reward_type === 'discount_amount' ? ` · ${rupiah(x.discount_value ?? 0)}` : ' · Item'}</option>)}</select>{reward && <p className="mt-3 rounded-xl bg-amber-50 p-3 text-xs text-amber-800">Reward ini akan tercatat dan stempel pelanggan direset setelah pesanan dibuat.</p>}</> : <p className="mt-2 text-xs text-slate-500">Pilih pelanggan untuk melihat reward aktif.</p>}</section><button className="btn-primary w-full" disabled={busy || !customer} onClick={() => void save()}>{busy ? 'Menyimpan pesanan...' : 'Simpan pesanan'}</button></aside>
    </div>
    <Modal open={customerOpen} title="Pilih pelanggan" onClose={() => setCustomerOpen(false)}><div className="space-y-4"><div className="relative"><Search className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400" size={17} /><input className="input pr-10" placeholder="Cari nama atau WhatsApp..." value={query} onChange={e => { setQuery(e.target.value); setPage(1) }} /></div>{customers.loading ? <LoadingState /> : customers.error ? <ErrorState message={customers.error} retry={customers.reload} /> : visible.length === 0 ? <EmptyState title="Pelanggan tidak ditemukan" /> : <div className="space-y-2">{visible.map(x => <button key={x.id} className="flex w-full items-center justify-between rounded-xl border border-sage-100 p-3 text-left hover:bg-sage-50" onClick={() => { setCustomer(x); setCustomerOpen(false) }}><span><b className="text-sm">{x.name}</b><small className="mt-1 block text-xs text-slate-500">{x.whatsapp}</small></span>{customer?.id === x.id && <Check size={17} className="text-emerald-600" />}</button>)}</div>}<div className="flex items-center justify-between border-t border-sage-100 pt-3 text-xs"><span>Halaman {page} / {pages}</span><div className="flex gap-1"><button className="rounded-lg p-2 hover:bg-sage-50" disabled={page <= 1} onClick={() => setPage(page - 1)}><ChevronLeft size={16} /></button><button className="rounded-lg p-2 hover:bg-sage-50" disabled={page >= pages} onClick={() => setPage(page + 1)}><ChevronRight size={16} /></button></div></div></div></Modal>
    <NewCustomerModal open={newCustomerOpen} onClose={() => setNewCustomerOpen(false)} onSaved={async (x) => { setCustomer(x); setNewCustomerOpen(false); await customers.reload() }} />
  </>
}

function NewCustomerModal({ open, onClose, onSaved }: { open: boolean; onClose: () => void; onSaved: (customer: Customer) => void }) { const [name, setName] = useState(''); const [whatsapp, setWhatsapp] = useState(''); const [address, setAddress] = useState(''); const [busy, setBusy] = useState(false); const save = async () => { if (name.trim().length < 2 || whatsapp.trim().length < 8) { toast.error('Nama dan WhatsApp wajib diisi'); return } setBusy(true); const result = await supabase.from('customers').insert({ name: name.trim(), whatsapp: whatsapp.trim(), address: address.trim() || null }).select('*').single(); setBusy(false); if (result.error) toast.error(result.error.message); else onSaved(result.data as Customer) }; return <Modal open={open} title="Tambah pelanggan" onClose={onClose}><div className="space-y-4"><label><span className="label">Nama lengkap</span><input className="input" value={name} onChange={e => setName(e.target.value)} /></label><label><span className="label">Nomor WhatsApp</span><input className="input" placeholder="08xxxxxxxxxx" value={whatsapp} onChange={e => setWhatsapp(e.target.value)} /></label><label><span className="label">Alamat</span><textarea className="input" value={address} onChange={e => setAddress(e.target.value)} /></label><button className="btn-primary w-full" disabled={busy} onClick={() => void save()}>{busy ? 'Menyimpan...' : 'Simpan pelanggan'}</button></div></Modal> }
