import { CheckCircle2, Gift, Pencil, Plus, Trash2 } from 'lucide-react'
import { useState } from 'react'
import { toast } from 'sonner'
import { PageHeader } from '../../components/admin/PageHeader'
import { ConfirmModal, EmptyState, ErrorState, LoadingState, Modal } from '../../components/ui'
import { useSupabaseList } from '../../hooks/useSupabaseList'
import { supabase } from '../../lib/supabase'
import type { Customer, Reward } from '../../types'

export function RewardsPage() {
  const { data, loading, error, reload } = useSupabaseList<Reward>('rewards', '*')
  const customers = useSupabaseList<Customer>('customers', '*')
  const [edit, setEdit] = useState<Partial<Reward> | null>(null)
  const [redeem, setRedeem] = useState<{ customer: string; reward: string } | null>(null)
  const [remove, setRemove] = useState<Reward | null>(null)
  const redemption = async () => { if (!redeem?.customer || !redeem.reward) return toast.error('Pilih pelanggan dan reward'); const { error: e } = await supabase.rpc('redeem_customer_reward', { p_customer_id: redeem.customer, p_reward_id: redeem.reward }); if (e) toast.error(e.message); else { toast.success('Reward berhasil digunakan'); setRedeem(null); await customers.reload() } }
  const del = async () => { if (remove) await supabase.from('rewards').delete().eq('id', remove.id); setRemove(null); await reload() }
  return <><PageHeader title="Reward diskon" description="Kelola diskon loyalitas yang dapat dipakai saat membuat pesanan." action={<div className="flex flex-wrap gap-2"><button className="btn-secondary" onClick={() => setRedeem({ customer: '', reward: '' })}><CheckCircle2 size={18} /> Gunakan reward</button><button className="btn-primary" onClick={() => setEdit({ name: '', description: '', stock: null, is_active: true, reward_type: 'discount_percent', discount_value: 10 })}><Plus size={18} /> Tambah diskon</button></div>} />
    {loading ? <LoadingState /> : error ? <ErrorState message={error} retry={reload} /> : data.length === 0 ? <EmptyState title="Belum ada reward diskon" /> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{data.filter(x => x.reward_type !== 'item').map(x => <article key={x.id} className="card p-5"><span className="grid size-12 place-items-center rounded-2xl bg-amber-50 text-amber-600"><Gift /></span><div className="mt-5 flex items-start justify-between gap-3"><div><h2 className="font-bold">{x.name}</h2><p className="mt-2 text-xs font-bold text-amber-700">{x.reward_type === 'discount_amount' ? `Potongan Rp${(x.discount_value ?? 0).toLocaleString('id-ID')}` : `Diskon ${x.discount_value ?? 0}%`}</p><p className="mt-2 min-h-10 text-sm text-slate-500">{x.description}</p></div><span className={`rounded-full px-3 py-1 text-[10px] font-bold ${x.is_active ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-500'}`}>{x.is_active ? 'Aktif' : 'Nonaktif'}</span></div><div className="mt-5 flex items-center justify-between border-t border-sage-100 pt-3"><p className="text-xs">Stok {x.stock ?? '∞'}</p><div><button className="p-2 text-sage-700" onClick={() => setEdit(x)}><Pencil size={17} /></button><button className="p-2 text-red-500" onClick={() => setRemove(x)}><Trash2 size={17} /></button></div></div></article>)}</div>}
    {edit && <RewardModal value={edit} onClose={() => setEdit(null)} onSaved={async () => { setEdit(null); await reload() }} />}
    <Modal open={!!redeem} title="Gunakan reward diskon" onClose={() => setRedeem(null)}><div className="space-y-4"><label><span className="label">Pelanggan dengan reward</span><select className="input" value={redeem?.customer} onChange={e => setRedeem({ ...redeem!, customer: e.target.value })}><option value="">Pilih pelanggan</option>{customers.data.filter(x => x.available_rewards > 0).map(x => <option key={x.id} value={x.id}>{x.name} ({x.available_rewards} tersedia)</option>)}</select></label><label><span className="label">Reward diskon</span><select className="input" value={redeem?.reward} onChange={e => setRedeem({ ...redeem!, reward: e.target.value })}><option value="">Pilih diskon</option>{data.filter(x => x.reward_type !== 'item' && x.is_active && (x.stock === null || (x.stock ?? 0) > 0)).map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><p className="rounded-xl bg-amber-50 p-3 text-xs leading-5 text-amber-800">Untuk memakai diskon pada pesanan baru, pilih diskon langsung di halaman tambah pesanan.</p><button className="btn-primary w-full" onClick={() => void redemption()}>Konfirmasi penggunaan</button></div></Modal>
    <ConfirmModal open={!!remove} title="Hapus reward?" description="Reward yang sudah memiliki riwayat penggunaan sebaiknya dinonaktifkan, bukan dihapus." danger confirmLabel="Hapus" onClose={() => setRemove(null)} onConfirm={() => void del()} />
  </>
}

function RewardModal({ value, onClose, onSaved }: { value: Partial<Reward>; onClose: () => void; onSaved: () => void }) {
  const [f, setF] = useState({ ...value, reward_type: value.reward_type === 'discount_amount' ? 'discount_amount' as const : 'discount_percent' as const })
  const save = async () => { if (!f.name) return toast.error('Nama reward wajib diisi'); if (!(Number(f.discount_value) > 0)) return toast.error('Isi nilai diskon lebih dari 0'); const payload = { name: f.name, description: f.description || null, stamp_cost: 5, stock: f.stock === null ? null : Number(f.stock), is_active: f.is_active ?? true, reward_type: f.reward_type, discount_value: f.reward_type === 'discount_percent' ? Math.min(100, Number(f.discount_value)) : Number(f.discount_value), item_name: null }; const result = f.id ? await supabase.from('rewards').update(payload).eq('id', f.id) : await supabase.from('rewards').insert(payload); if (result.error) toast.error(result.error.message); else { toast.success('Reward diskon disimpan'); onSaved() } }
  return <Modal open title={f.id ? 'Edit reward diskon' : 'Tambah reward diskon'} onClose={onClose}><div className="space-y-4"><div className="rounded-2xl bg-sage-50 p-4 text-sm leading-6 text-slate-600"><b className="text-sage-800">Cara kerja</b><p className="mt-1">Diskon aktif bisa dipilih admin saat membuat pesanan. Setelah dipakai, reward berkurang satu dan stempel pelanggan direset.</p></div><label><span className="label">Nama diskon</span><input className="input" placeholder="Contoh: Diskon pelanggan loyal" value={f.name ?? ''} onChange={e => setF({ ...f, name: e.target.value })} /></label><label><span className="label">Tipe diskon</span><select className="input" value={f.reward_type} onChange={e => setF({ ...f, reward_type: e.target.value as 'discount_percent' | 'discount_amount', discount_value: 0 })}><option value="discount_percent">Persentase (%)</option><option value="discount_amount">Nominal (Rp)</option></select></label><label><span className="label">{f.reward_type === 'discount_percent' ? 'Besar diskon (%)' : 'Besar potongan (Rp)'}</span><input type="number" min="1" max={f.reward_type === 'discount_percent' ? 100 : undefined} className="input" placeholder={f.reward_type === 'discount_percent' ? 'Contoh: 10' : 'Contoh: 50000'} value={f.discount_value || ''} onChange={e => setF({ ...f, discount_value: Number(e.target.value) || 0 })} /><small className="mt-1 block text-xs text-slate-500">{f.reward_type === 'discount_percent' ? '10 berarti diskon 10% dari total pesanan.' : '50000 berarti potongan Rp50.000.'}</small></label><label><span className="label">Keterangan (opsional)</span><textarea className="input min-h-20" placeholder="Syarat atau detail diskon" value={f.description ?? ''} onChange={e => setF({ ...f, description: e.target.value })} /></label><label><span className="label">Stok (kosong = tidak terbatas)</span><input type="number" min="0" className="input" placeholder="Tidak terbatas" value={f.stock ?? ''} onChange={e => setF({ ...f, stock: e.target.value === '' ? null : Number(e.target.value) })} /></label><label className="flex gap-3 text-sm"><input type="checkbox" checked={f.is_active ?? true} onChange={e => setF({ ...f, is_active: e.target.checked })} /> Diskon aktif</label><button className="btn-primary w-full" onClick={() => void save()}>Simpan diskon</button></div></Modal>
}
