import { Eye, EyeOff, Pencil, Plus, Scissors, Trash2 } from 'lucide-react'
import { useState } from 'react'
import { toast } from 'sonner'
import { PageHeader } from '../../components/admin/PageHeader'
import { ConfirmModal, EmptyState, ErrorState, LoadingState, Modal } from '../../components/ui'
import { useSupabaseList } from '../../hooks/useSupabaseList'
import { supabase } from '../../lib/supabase'
import { rupiah } from '../../lib/utils'
import type { Service } from '../../types'
export function ServicesPage(){const {data,loading,error,reload}=useSupabaseList<Service>('services','*','sort_order');const [edit,setEdit]=useState<Partial<Service>|null>(null);const [remove,setRemove]=useState<Service|null>(null);const toggle=async(x:Service)=>{await supabase.from('services').update({is_active:!x.is_active}).eq('id',x.id);await reload()};const del=async()=>{if(remove)await supabase.from('services').delete().eq('id',remove.id);setRemove(null);toast.success('Layanan dihapus');await reload()};return <><PageHeader title="Layanan" description="Atur jenis layanan dan harga awal yang tampil untuk publik." action={<button className="btn-primary" onClick={()=>setEdit({name:'',description:'',starting_price:0,icon:'scissors',is_active:true,sort_order:data.length+1})}><Plus size={18}/> Tambah layanan</button>}/>{loading?<LoadingState/>:error?<ErrorState message={error} retry={reload}/>:data.length===0?<EmptyState/>:<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{data.map(x=><article key={x.id} className="card p-5"><div className="flex justify-between"><span className="grid size-11 place-items-center rounded-2xl bg-sage-100 text-sage-700"><Scissors size={20}/></span><span className={`h-fit rounded-full px-3 py-1 text-[10px] font-bold ${x.is_active?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-500'}`}>{x.is_active?'Aktif':'Nonaktif'}</span></div><h2 className="mt-5 text-lg font-bold">{x.name}</h2><p className="mt-2 min-h-12 text-sm leading-6 text-slate-500">{x.description}</p><p className="mt-4 text-sm">Mulai <b className="text-sage-700">{rupiah(x.starting_price)}</b></p><div className="mt-5 flex justify-end gap-1 border-t border-sage-100 pt-3"><button className="p-2 text-slate-500" onClick={()=>void toggle(x)}>{x.is_active?<EyeOff size={18}/>:<Eye size={18}/>}</button><button className="p-2 text-sage-700" onClick={()=>setEdit(x)}><Pencil size={18}/></button><button className="p-2 text-red-500" onClick={()=>setRemove(x)}><Trash2 size={18}/></button></div></article>)}</div>}{edit&&<ServiceModal value={edit} onClose={()=>setEdit(null)} onSaved={async()=>{setEdit(null);await reload()}}/>}<ConfirmModal open={!!remove} title="Hapus layanan?" description="Layanan akan dihapus permanen." danger confirmLabel="Hapus" onClose={()=>setRemove(null)} onConfirm={()=>void del()}/></>}
function ServiceModal({value,onClose,onSaved}:{value:Partial<Service>;onClose:()=>void;onSaved:()=>void}){const [f,setF]=useState(value);const save=async()=>{if(!f.name){toast.error('Nama wajib diisi');return}const payload={name:f.name,description:f.description||null,starting_price:Number(f.starting_price)||null,icon:f.icon||'scissors',is_active:f.is_active??true,sort_order:Number(f.sort_order)||0};const {error}=f.id?await supabase.from('services').update(payload).eq('id',f.id):await supabase.from('services').insert(payload);if(error)toast.error(error.message);else{toast.success('Layanan disimpan');onSaved()}};return <Modal open title={f.id?'Edit layanan':'Tambah layanan'} onClose={onClose}><div className="space-y-4"><label><span className="mb-2 block text-xs font-bold">Nama layanan</span><input className="input" value={f.name??''} onChange={e=>setF({...f,name:e.target.value})}/></label><label><span className="mb-2 block text-xs font-bold">Deskripsi</span><textarea className="input" value={f.description??''} onChange={e=>setF({...f,description:e.target.value})}/></label><div className="grid grid-cols-2 gap-3"><label><span className="mb-2 block text-xs font-bold">Harga mulai</span><input type="number" className="input" value={f.starting_price??0} onChange={e=>setF({...f,starting_price:Number(e.target.value)})}/></label><label><span className="mb-2 block text-xs font-bold">Urutan</span><input type="number" className="input" value={f.sort_order??0} onChange={e=>setF({...f,sort_order:Number(e.target.value)})}/></label></div><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={f.is_active??true} onChange={e=>setF({...f,is_active:e.target.checked})}/> Layanan aktif</label><button className="btn-primary w-full" onClick={()=>void save()}>Simpan layanan</button></div></Modal>}
